```{r setup, include=FALSE}
# Set default behavior for all code chunks here:
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE, 
  warning = FALSE, 
  fig.width = 16/2, 
  fig.height = 9/2
)

# Run this command only once to install my forestecology package, specifically
# the "SCBI" branch:
# devtools::install_github("rudeboybert/forestecology)

# Load all your used packages here:
library(tidyverse)
library(broom)
library(moderndive)
library(patchwork)
library(forestecology)
library(sf)
library(knitr)

# Set seed value of random number generator here:
set.seed(76)
```

## SCBI Data

```{r}
# From forestecology package
# devtools::install_github("rvalavi/blockCV")
library(blockCV)
library(sfheaders)

scbi_2013 <- read.csv("data/scbi.stem2.csv") %>% 
  select(treeID, stemID, sp, quadrat, gx, gy, dbh, date = ExactDate, codes, status) %>%
  mutate(date = lubridate::mdy(date)) %>%
  filter(gx < 300, gy > 300, gy < 600)

scbi_2018 <- read.csv("data/scbi.stem3.csv") %>% 
  select(treeID, stemID, sp, quadrat, gx, gy, dbh, date = ExactDate, codes, status) %>%
  mutate(date = lubridate::mdy(date),
         dbh = as.numeric(dbh)) %>%
  filter(gx < 300, gy > 300, gy < 600)

census_df1 <- scbi_2013 
census_df2 <- scbi_2018
id <- "stemID"

cluster_names <- data.frame(group = c(1:7), group_name = c("high_sla", "low_sla", "shrubs", "tall_light_wood", "evergreens", "oaks", "other"), group_alias = c("High SLA trees", "Low SLA trees", "Shrubs", "Tall trees - Light wood", "Evergreens", "Oaks", "Other"))

spptable <- read_csv("data/scbi.spptable.csv") %>% 
  left_join(cluster_names, by = "group") %>% 
  mutate(group = ifelse(is.na(group), 7, group),
         group_name = ifelse(group == 7, "other", group_name),
         group_alias = ifelse(group == 7, "Other", group_alias))

scbi_growth_df <- 
  # Merge both censuses and compute growth:
  compute_growth(census_df1, census_df2, id) %>%
  # Convert growth from cm to mm to make result comparable
  mutate(growth = growth/10,
             sp = as.factor(sp)) %>% 
  inner_join(spptable, by = "sp") %>% 
  filter(status == "A")
```

```{r}
# Add spatial information
cv_fold_size <- 100
max_dist <- 7.5

scbi_study_region <- 
 #tibble(x = c(0,400,400,0,0), y = c(0,0,640,640,0)) %>% 
  tibble(x = c(0,300,300,0,0), y = c(300,300,600,600,3)) %>% 
  sfc_polygon()

# Add buffer variable to data frame
scbi_growth_df <- scbi_growth_df %>%
  add_buffer_variable(direction = "in", size = max_dist, region = scbi_study_region)

scbi_cv_grid <- spatialBlock(
  speciesData = scbi_growth_df, theRange = 100, yOffset = 0.9999, k = 9, verbose = FALSE)

# Add foldID to data
scbi_growth_df <- scbi_growth_df %>% 
  mutate(
    foldID = scbi_cv_grid$foldID
  )

# Visualize grid
scbi_cv_grid$plots +
  geom_sf(data = scbi_growth_df, aes(col=factor(foldID)), size = 0.1)

scbi_cv_grid_sf <- scbi_cv_grid$blocks %>%
  st_as_sf()
```

# Create focal vs. competitor data
```{r}
focal_vs_comp_scbi <- scbi_growth_df %>% 
  create_focal_vs_comp(max_dist, cv_grid_sf = scbi_cv_grid_sf, id = "stemID")

focal_vs_comp_scbi <- focal_vs_comp_scbi %>% 
  left_join(select(spptable, sp, focal_group = group_name), by = c("focal_sp" = "sp")) %>% 
  left_join(select(spptable, sp, comp_group = group_name), by = c("comp_sp" = "sp"))

```

# Spread into wide form for modeling (note: should we do this by genus?)

```{r}
focal_vs_comp_scbi_wide <- focal_vs_comp_scbi %>% 
  group_by(focal_ID, focal_group, dbh, foldID, growth, comp_group) %>%
  summarize(comp_basal_area = sum(comp_basal_area)) %>% 
  pivot_wider(names_from = comp_group, values_from = comp_basal_area, values_fill = 0)

group_order <- focal_vs_comp_scbi_wide %>% 
  ungroup() %>% 
  filter(focal_group != "other") %>% 
  count(focal_group, sort = T)

# set factor order by largest group
focal_vs_comp_scbi_wide <- focal_vs_comp_scbi_wide %>% 
  mutate(focal_group = factor(focal_group, levels = c(as.character(group_order$focal_group), "other")))
head(focal_vs_comp_scbi_wide)
# write_csv(focal_vs_comp_scbi_wide, "data/focal_vs_comp_scbi_wide.csv")
```

# Model

```{r}
model <- lm(growth ~ dbh + focal_group + high_sla + low_sla + tall_light_wood + evergreens + oaks + shrubs + other, data = focal_vs_comp_scbi_wide)

summary(model)
```
$$
y = \beta_0 + \beta_1d_f + \beta_2g_f + \sum_{g=1}^G \beta_{g}m_g + \varepsilon \\
\text{ where } d_f \text{ is the diameter at breast height of the focal tree, } g_f \text{ is the cluster group of the focal tree, } \\ g \in \{\text{tall trees/light wood, high SLA trees, low SLA trees, shrubs, oaks, evergreens, other}\}, \\ \text{ and } m_g \text{ is the biomass of all competitor trees of the specific focal group. Coefficients are with respect to tall trees/light wood}
$$

Plot all trees in SCBI plot:

```{r}
scbi_growth_subset <- scbi_growth_df %>% 
  filter(stemID %in% focal_vs_comp_scbi_wide$focal_ID)

ggplot(data = scbi_growth_subset) +
  geom_sf(aes(col = sp), size = 0.5) +
  labs(title = "All trees in SCBI site")

ggplot(data = scbi_growth_subset) +
  geom_sf(aes(col = Genus), size = 0.5) +
  labs(title = "All trees in SCBI site")

ggplot(data = scbi_growth_subset) +
  geom_sf(aes(col = Family), size = 0.5) +
  labs(title = "All trees in SCBI site")

ggplot(data = scbi_growth_subset) +
  geom_sf(aes(col = factor(group_alias)), size = 0.5) +
  labs(title = "All trees in SCBI site")
```

Plot all the trees, specific species

```{r}
ggplot(data = scbi_growth_df %>% filter(sp == "nysy")) +
  geom_sf(aes(col = sp), size = 0.5)+
  labs(title = "All Nyssa sylvatica trees in Michigan Big Woods site")

ggplot(data = scbi_growth_df %>% filter(sp == "astr")) +
  geom_sf(aes(col = sp), size = 0.5)+
  labs(title = "All Asimina triloba trees in Michigan Big Woods site")
```